/// <reference types = "cypress"/>
describe('first suite', () => {
    beforeEach('before each', () => {
        Cypress.Cookies.preserveOnce('firstCookie')
    })
    it('first test', () => {
        // cy.visit('https://example.com')
        // cy.visit('https://google.com')
        // cy.visit('example.com')
        // cy.visit('venue')
        cy.log(Cypress.env('firstCookieValue'))
        cy.setCookie('firstCookie', Cypress.env('firstCookieValue'))
        cy.visit('cypress/fixtures/registration.html', {timeout : 120000})
        cy.get('#name').as('nameAlias')
        cy.get('#name').parent().find('label').should('have.text', 'Name')
        cy.get('@nameAlias').clear().type('my name')
        cy.screenshot()
        cy.get('.email').type('example@example.com')
        cy.get('#country').select('Spain').find(':selected').should('have.text', 'Spain')
        cy.screenshot('newNameForScreenshot')
        cy.get('#city').select(['Malaga', 'Valencia']).find(':selected').then(($selectedOnes) => {
            expect($selectedOnes).to.have.length(2)
            expect($selectedOnes[0]).to.have.text('Malaga')
            expect($selectedOnes[1]).to.have.text('Valencia')
        })
        cy.get('#city').screenshot()
        cy.get('[type="date"]').type('2022-06-01')
        // cy.get('[type="radio"]').first()
        // cy.get('[type="radio"]').last()
        cy.get('[type="radio"]').eq(2).check()
        cy.get('[type="radio"]').eq(2).should('be.checked').and('have.attr', 'value', 'Monthly')
        cy.get('[type="checkbox"]').should('have.length', 2)
        cy.get('[type="checkbox"]').check()
        cy.get('[type="submit"]').click()
        // cy.get('[type="submit"]').parent().find('span')
        // cy.get('[type="submit"]').siblings()
        cy.get('form').submit()

        cy.contains('Accept our cookie policy').should('have.attr', 'href', 'cookiePolicy.html')
        cy.getCookie('firstCookie').then(($theCookie) => {
            expect($theCookie.value).to.eq(Cypress.env('firstCookieValue'))
            expect($theCookie.domain).to.contain('local')
        })
    })
    it('second test', () => {
        // cy.getCookies().should('have.length', 1)
        cy.getCookies().then(($theCookies) => {
            expect($theCookies).to.have.length(1)
            expect($theCookies[0].name).to.eq('firstCookie')
        })
        Cypress.env('secondCookieValue', 'secondValue')
        cy.log(Cypress.env('secondCookieValue'))
        cy.setCookie('secondCookie', Cypress.env('secondCookieValue'))
        cy.getCookies().should('have.length', 2)
        cy.clearCookie('firstCookie')
        cy.getCookies().then(($theNewCookies) => {
            expect($theNewCookies).to.have.length(1)
            expect($theNewCookies[0].name).to.eq('secondCookie')
        })
        cy.clearCookies()
        cy.getCookies().should('have.length', 0)
    })
})